<section class="section-block--tight bg-orange overflow-hidden">
  <div class="ticker-track flex gap-8 sm:gap-12 whitespace-nowrap py-2">
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Renovasi Rumah</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Bangun Baru</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Pagar & Kanopi</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Plafon Gypsum</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Keramik Lantai</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Pengecatan</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Instalasi Pipa</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Atap Baja Ringan</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Renovasi Rumah</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Bangun Baru</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Pagar & Kanopi</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Plafon Gypsum</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Keramik Lantai</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Pengecatan</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Instalasi Pipa</span>
    <span class="text-fg text-xl opacity-60">◆</span>
    <span class="font-heading text-fg text-xl sm:text-2xl tracking-wider">Atap Baja Ringan</span>
  </div>
</section>
